version: "3.9"
# Указываем версию синтаксиса Docker Compose. 3.9 — актуальная для современных версий Docker.

services:
  flask-app:
    # Определяем сервис с именем flask-app, это будет наш контейнер с Flask приложением

    build: .
    # Инструкция build говорит Docker собрать образ из текущей директории (там должен быть Dockerfile)

    ports:
      - "8000:5000"
    # Проброс портов:
    # - первый порт (8000) — порт на хосте (твой компьютер)
    # - второй порт (5000) — порт внутри контейнера, на котором Flask по умолчанию слушает
    # Таким образом, заходя на http://localhost:8000, мы попадаем на Flask-приложение внутри контейнера

    volumes:
      - .:/app
    # Монтируем текущую директорию хоста (.) в папку /app внутри контейнера
    # Это нужно, чтобы изменения в коде на хосте сразу отражались в контейнере без пересборки

    environment:
      - FLASK_ENV=development
    # Задаём переменные окружения внутри контейнера
    # FLASK_ENV=development — включает режим разработки Flask (отладчик, автообновление кода)
